name: handyman
description: An artisan search application.

publish_to: "github.com"

authors:
  - "Quabynah Codelabs LLC <codelbas.quabynah@gmail.com>"

version: 1.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  algolia: ^0.1.7
  auto_route: ^0.6.7
  badges: ^1.1.1
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.1.0
  cloud_firestore: ^0.14.3
  contact_picker: ^0.0.2
  cupertino_icons: ^0.1.3
  email_validator: ^1.0.4
  file_picker: ^2.0.11
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.2
  firebase_remote_config: ^0.4.0
  firebase_storage: ^4.0.0
  flutter_google_places: ^0.2.6
  flutter_icons: ^1.0.0+1
  flutter_image_compress: ^0.6.5+1
  flutter_isolate: ^1.0.0+14
  flutter_local_notifications: ^1.4.3
  flutter_rating_bar: ^3.0.1+1
  flutter_staggered_animations: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg_provider: ^0.1.6
  geocoder: ^0.2.1
  geolocator: ^6.0.0
  get_it: ^4.0.4
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.28+1
  google_maps_webservice: ^0.0.18
  google_sign_in: ^4.5.1
  image_cropper: ^1.2.1
  image_picker: ^0.6.1+10
  intl: ^0.16.1
  jiffy: ^3.0.1
  json_annotation: ^3.0.1
  md2_tab_indicator: ^1.0.2
  moor: ^3.1.0
  path: ^1.7.0
  path_provider: ^1.6.8
  permission_handler: ^5.0.0+hotfix.3
  photo_view: ^0.10.2
  provider: ^4.0.4
  random_color: ^1.0.5
  share: ^0.6.4+2
  shared_preferences: ^0.5.10
  sliding_sheet: ^0.3.3
  sqlite3_flutter_libs: ^0.2.0
  table_calendar: ^2.2.3
  url_launcher: ^5.7.2
  uuid: ^2.0.4
  wakelock: ^0.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^1.10.2
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.4
  json_serializable: ^3.2.0
  moor_generator: ^3.3.1

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo_colored.png"

flutter:
  uses-material-design: true
  # https://flutter.dev/docs/development/ui/assets-and-images
  assets:
    - assets/
    - assets/logo/
    - assets/bg/bg.webp
    - assets/bg/2x/bg.webp
    - assets/bg/3x/bg.webp
    - assets/svg/
