name: lite

description: App for customers on the HandyMan mobile platform (lite version)

repository: "https://github.com/Quabynah-Codelabs/handyman"

authors:
  - "Quabynah Bilson <codelbas.quabynah@gmail.com>"

documentation: "https://github.com/Quabynah-Codelabs/handyman/docs"

issue_tracker: "https://github.com/Quabynah-Codelabs/handyman/issues"

publish_to: "github.com"

version: 0.0.9+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^0.1.7
  auto_route: ^0.6.7
  bloc: ^6.1.1
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.1.0
  circular_reveal_animation: ^1.1.5
  contact_picker: null
  cupertino_icons: ^0.1.2
  day_night_time_picker: null
  dio: ^3.0.10
  email_validator: ^1.0.4
  equatable: ^1.2.5
  file_picker: ^2.1.5
  #  firebase_messaging:
  #  firebase_storage:
  #  firebase_auth:
  #  firebase_analytics: ^5.0.2
  #  firebase_core: ^0.4.0+9
  #  cloud_firestore: ^0.12.9+5
  cloud_firestore: ^0.16.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  firebase_storage: ^7.0.0
  flutter_bloc: ^6.1.1
  flutter_dotenv: ^2.1.0
  flutter_icons: ^1.0.0+1
  line_awesome_flutter: ^1.0.1
  flutter_image_compress: ^0.6.5+1
  flutter_local_notifications: ^3.0.3
  flutter_rating_bar: null
  flutter_riverpod: ^0.12.1
  flutter_spinkit: ^4.1.2+1
  flutter_svg_provider: ^0.1.6
  flutter_video_compress: ^0.3.7+8
  geocoder: ^0.2.1
  geolocator: ^6.0.0+4
  get_version: ^0.2.2
  google_fonts: ^1.1.0
  google_maps_flutter: ^1.0.10
  google_maps_place_picker: ^1.0.1
  google_maps_webservice: null
  google_sign_in: ^4.5.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  image_cropper: ^1.2.1
  image_picker: ^0.6.1+10
  intl: ^0.16.1
  jiffy: ^3.0.1
  json_annotation: ^3.0.1
  open_mail_app: ^0.0.3
  otp_text_field: ^1.0.1
  path: ^1.7.0
  path_provider: ^1.6.8
  permission_handler: ^5.0.0+hotfix.3
  reading_time: ^1.0.0+2
  share: ^0.6.4+2
  shared_preferences: ^0.5.10
  sliding_sheet: ^0.3.3
  super_enum: ^0.5.0
  url_launcher: ^5.7.2
  uuid: ^2.0.4
  wakelock: ^0.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  bloc_test: ^7.1.0
  build_runner: ^1.10.10
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  hive_generator: ^0.8.2
  json_serializable: ^3.2.0
  logger: ^0.9.4
  mockito: ^4.1.3
  pedantic: ^1.9.2
  super_enum_generator: ^0.6.0

# app icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"

# app name
flutter_launcher_name:
  name: "HandyMan"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/svg/
    - .env
