name: lite

description: App for customers on the HandyMan mobile platform (lite version)

repository: "https://github.com/Quabynah-Codelabs/handyman"

authors:
  - "Quabynah Bilson <codelbas.quabynah@gmail.com>"

documentation: "https://github.com/Quabynah-Codelabs/handyman/docs"

issue_tracker: "https://github.com/Quabynah-Codelabs/handyman/issues"

publish_to: "github.com"

version: 1.2.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  algolia: ^0.1.7
  auto_route: ^0.6.7
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.1.0
  cloud_firestore: ^0.14.0+2
  email_validator: ^1.0.4
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.2
  firebase_storage: ^4.0.0
  flutter_icons: ^1.0.0+1
  flutter_image_compress: ^0.6.5+1
  flutter_local_notifications: ^1.4.3
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_animations: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg_provider: ^0.1.6
  flutter_video_compress: ^0.3.7+8
  geolocator: ^5.3.2+2
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  image_cropper: ^1.2.1
  image_picker: ^0.6.1+10
  intl: ^0.16.1
  jiffy: ^3.0.1
  json_annotation: ^3.0.1
  open_mail_app: ^0.0.3
  otp_text_field: ^1.0.1
  path: ^1.7.0
  path_provider: ^1.6.8
  permission_handler: ^5.0.0+hotfix.3
  flutter_riverpod: ^0.12.1
  reading_time: ^1.0.0+2
  share: ^0.6.4+2
  shared_preferences: ^0.5.10
  sliding_sheet: ^0.3.3
  url_launcher: ^5.7.2
  uuid: ^2.0.4
  wakelock: ^0.1.4+2
  equatable: ^1.2.5
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  super_enum: ^0.5.0
  circular_reveal_animation: ^1.1.5
  flutter_rating_bar:
  contact_picker:
  geocoder:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  logger: ^0.9.4
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.10
  flutter_launcher_icons: ^0.7.4
  hive_generator: ^0.8.2
  super_enum_generator: ^0.6.0
  json_serializable: ^3.2.0
  mockito: ^4.1.3
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bg/
    - assets/logo/
    - assets/svg/