name: lite

description: App for customers on the HandyMan mobile platform (lite version)

repository: "https://github.com/Quabynah-Codelabs/handyman"

authors:
  - "Quabynah Bilson <codelbas.quabynah@gmail.com>"

documentation: "https://github.com/Quabynah-Codelabs/handyman/docs"

issue_tracker: "https://github.com/Quabynah-Codelabs/handyman/issues"

publish_to: "github.com"

version: 0.0.7+7

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^1.0.0+1
  auto_route: ^1.0.0-beta.10
  bloc: ^7.0.0-nullsafety.3
  cached_network_image: ^3.0.0-nullsafety
  carousel_slider: 4.0.0-nullsafety.0
  circular_reveal_animation: ^2.0.0-nullsafety.1
  contact_picker: ^0.0.2
  cupertino_icons: ^1.0.2
  day_night_time_picker: ^0.5.0
  email_validator: ^2.0.0-nullsafety
  #  todo -> remove after super_enum nullsafety
  equatable:
  #  equatable: ^2.0.0
  file_picker: ^3.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  flutter_bloc: ^7.0.0-nullsafety.3
  flutter_dotenv: ^4.0.0-nullsafety.0
  flutter_icons: ^1.1.0
  line_awesome_flutter: ^1.0.1
  flutter_image_compress: ^1.0.0-nullsafety
  flutter_local_notifications: ^5.0.0-nullsafety.0
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: ^0.13.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_video_compress: ^0.3.7+8
  geocoder: ^0.2.1
  geolocator: ^7.0.1
  get_version: ^0.2.2
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.1
  #  google_maps_place_picker: ^1.0.1
  google_places_picker: ^3.0.0-nullsafety.0
  google_maps_webservice: ^0.0.20-nullsafety.0
  google_sign_in: ^5.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^0.13.0
  image_cropper: ^1.3.1
  image_picker: ^0.7.2
  intl: ^0.17.0
  jiffy: ^4.0.0
  json_annotation: ^4.0.0
  open_mail_app: ^0.1.0-nullsafety.3
  otp_text_field: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.1
  provider: ^5.0.0-nullsafety.5
  permission_handler: ^6.0.1
  reading_time: ^1.0.0+2
  share: ^2.0.0
  shared_preferences: ^2.0.3
  sliding_sheet: ^0.4.1
  super_enum: ^0.5.0
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  wakelock: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^1.0.0-beta.11
  bloc_test: ^8.0.0-nullsafety.1
  build_runner: ^1.11.5
  #  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.0.0
  json_serializable: ^4.0.2
  logger: ^0.9.4
  mockito: ^5.0.0
  pedantic: ^1.11.0
  super_enum_generator: ^0.6.0

# app icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/svg/
    - .env
